[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

[rpc_endpoints]
arctestnet = "https://rpc-arc.testnet.circle.com"

[etherscan]
arctestnet = { key = "", url = "https://testnet.arcscan.app/api" }
